[package]
name = "smite-nyx-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
links = "nyx_agent"
description = "Low-level FFI bindings to the Nyx agent for smite"

[lints]
workspace = true

[build-dependencies]
cc = "1.0"
